replicas:
  _default: 1
  dev: 1

selector : dev

name:
  app: delivery-helm

service:
  nameApp: delivery-helm-service
  portName: port-delivery
  type: NodePort
  port: 80
  targetPort: 8002

kafka:
  portName: port-delivery-kafka
  type: NodePort
  port: 9092
  targetPort: 9092
  bootstrap: kafka:9092

image:
  repository: bobah165/delivery
  tag: v10

ingress:
  enabled: false
  name: "delivery-service-helm-ingress"
  className: nginx
  host: "arch.homework"
  pathType: Prefix
  path:
    delivery: /api/delivery

db:
  url: jdbc:postgresql://my-db-postgresql:5432/postgres

app:
  db:
    password:
      _default: cG9zdGdyZXM=
    username:
      _default: cG9zdGdyZXM=

